services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: watch_user
      POSTGRES_PASSWORD: watch_pass
      POSTGRES_DB: ecommerce_watch
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  worker:
    build: .
    command: celery -A app.workers.celery_app worker --loglevel=info --pool=solo
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  beat:
    build: .
    command: celery -A app.workers.celery_app beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
