services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: watch_user
      POSTGRES_PASSWORD: watch_pass
      POSTGRES_DB: ecommerce_watch
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"


volumes:
  postgres_data:
