"""add indexes and unique url

Revision ID: 386f90c30b50
Revises: 409eca1a7e2e
Create Date: 2026-07-09 19:04:40.024596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386f90c30b50'
down_revision: Union[str, Sequence[str], None] = '409eca1a7e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_price_snapshots_product_scraped', 'price_snapshots', ['product_id', 'scraped_at'], unique=False)
    op.create_unique_constraint(None, 'products', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_index('ix_price_snapshots_product_scraped', table_name='price_snapshots')
    # ### end Alembic commands ###
